In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv('age_gender.csv')

In [41]:
data = df.drop(['img_name','age','ethnicity'],axis= 1)
data

gender                                             pixels
0           0  129 128 128 126 127 130 133 135 139 142 145 14...
1           0  164 74 111 168 169 171 175 182 184 188 193 199...
2           0  67 70 71 70 69 67 70 79 90 103 116 132 145 155...
3           0  193 197 198 200 199 200 202 203 204 205 208 21...
4           0  202 205 209 210 209 209 210 211 212 214 218 21...
...       ...                                                ...
23700       1  127 100 94 81 77 77 74 99 102 98 128 145 160 1...
23701       1  23 28 32 35 42 47 68 85 98 103 113 117 130 129...
23702       1  59 50 37 40 34 19 30 101 156 170 177 184 187 1...
23703       1  45 108 120 156 206 197 140 180 191 199 204 207...
23704       1  156 161 160 165 170 173 166 177 183 191 187 18...

[23705 rows x 2 columns]

In [42]:
data['pixels']=data['pixels'].apply(lambda x:  np.array(x.split(), dtype="float32"))


data['pixels'] = data['pixels'].apply(lambda x: x/255)
data

gender                                             pixels
0           0  [0.5058824, 0.5019608, 0.5019608, 0.49411765, ...
1           0  [0.6431373, 0.2901961, 0.43529412, 0.65882355,...
2           0  [0.2627451, 0.27450982, 0.2784314, 0.27450982,...
3           0  [0.75686276, 0.77254903, 0.7764706, 0.78431374...
4           0  [0.7921569, 0.8039216, 0.81960785, 0.8235294, ...
...       ...                                                ...
23700       1  [0.49803922, 0.39215687, 0.36862746, 0.3176470...
23701       1  [0.09019608, 0.10980392, 0.1254902, 0.13725491...
23702       1  [0.23137255, 0.19607843, 0.14509805, 0.1568627...
23703       1  [0.1764706, 0.42352942, 0.47058824, 0.6117647,...
23704       1  [0.6117647, 0.6313726, 0.627451, 0.64705884, 0...

[23705 rows x 2 columns]

In [43]:
data = data.to_numpy()



In [44]:

img = data[:,1:]

data_2d = np.vstack(img)

X = np.array([x[0] for x in img])
# Print the resulting 2D NumPy array
y = data[:, 0].astype(int)
# from sklearn.decomposition import PCA

# # Create a PCA instance with the desired number of components
# n_components = 500 # Adjust this based on the number of components you want to keep
# pca = PCA(n_components=n_components)
# # Fit the PCA model to your data and transform it
# X = pca.fit_transform(X)

X.shape

(23705, 2304)

In [45]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

k = 20 # Number of neighbors
knn_classifier = KNeighborsClassifier(n_neighbors=k)

knn_classifier.fit(X_train, y_train)

y_pred = knn_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Classification Report:\n", report)
print("Confusion Matrix:\n", conf_matrix)


Accuracy: 0.7344442100822611
Classification Report:
               precision    recall  f1-score   support

           0       0.70      0.85      0.77      2468
           1       0.79      0.61      0.69      2273

    accuracy                           0.73      4741
   macro avg       0.75      0.73      0.73      4741
weighted avg       0.74      0.73      0.73      4741

Confusion Matrix:
 [[2095  373]
 [ 886 1387]]


### Ethnicity Prediction

In [3]:
data = df.drop(['img_name','age','gender'],axis= 1)
data

ethnicity                                             pixels
0              2  129 128 128 126 127 130 133 135 139 142 145 14...
1              2  164 74 111 168 169 171 175 182 184 188 193 199...
2              2  67 70 71 70 69 67 70 79 90 103 116 132 145 155...
3              2  193 197 198 200 199 200 202 203 204 205 208 21...
4              2  202 205 209 210 209 209 210 211 212 214 218 21...
...          ...                                                ...
23700          0  127 100 94 81 77 77 74 99 102 98 128 145 160 1...
23701          1  23 28 32 35 42 47 68 85 98 103 113 117 130 129...
23702          2  59 50 37 40 34 19 30 101 156 170 177 184 187 1...
23703          2  45 108 120 156 206 197 140 180 191 199 204 207...
23704          0  156 161 160 165 170 173 166 177 183 191 187 18...

[23705 rows x 2 columns]

In [4]:
data['pixels']=data['pixels'].apply(lambda x:  np.array(x.split(), dtype="float32"))


data['pixels'] = data['pixels'].apply(lambda x: x/255)
data

ethnicity                                             pixels
0              2  [0.5058824, 0.5019608, 0.5019608, 0.49411765, ...
1              2  [0.6431373, 0.2901961, 0.43529412, 0.65882355,...
2              2  [0.2627451, 0.27450982, 0.2784314, 0.27450982,...
3              2  [0.75686276, 0.77254903, 0.7764706, 0.78431374...
4              2  [0.7921569, 0.8039216, 0.81960785, 0.8235294, ...
...          ...                                                ...
23700          0  [0.49803922, 0.39215687, 0.36862746, 0.3176470...
23701          1  [0.09019608, 0.10980392, 0.1254902, 0.13725491...
23702          2  [0.23137255, 0.19607843, 0.14509805, 0.1568627...
23703          2  [0.1764706, 0.42352942, 0.47058824, 0.6117647,...
23704          0  [0.6117647, 0.6313726, 0.627451, 0.64705884, 0...

[23705 rows x 2 columns]

In [5]:
data = data.to_numpy()



In [6]:

img = data[:,1:]

data_2d = np.vstack(img)

X = np.array([x[0] for x in img])
# Print the resulting 2D NumPy array
y = data[:, 0].astype(int)
# from sklearn.decomposition import PCA

# # Create a PCA instance with the desired number of components
# n_components = 500 # Adjust this based on the number of components you want to keep
# pca = PCA(n_components=n_components)
# # Fit the PCA model to your data and transform it
# X = pca.fit_transform(X)

X.shape

(23705, 2304)

In [7]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

k = 20 # Number of neighbors
knn_classifier = KNeighborsClassifier(n_neighbors=k)

knn_classifier.fit(X_train, y_train)

y_pred = knn_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Classification Report:\n", report)
print("Confusion Matrix:\n", conf_matrix)


Accuracy: 0.5406032482598608
Classification Report:
               precision    recall  f1-score   support

           0       0.53      0.90      0.66      2047
           1       0.67      0.45      0.54       904
           2       0.56      0.22      0.31       657
           3       0.46      0.21      0.29       804
           4       0.20      0.02      0.03       329

    accuracy                           0.54      4741
   macro avg       0.48      0.36      0.37      4741
weighted avg       0.52      0.54      0.48      4741

Confusion Matrix:
 [[1836   80   63   62    6]
 [ 407  409   11   69    8]
 [ 437   37  144   36    3]
 [ 545   60   24  168    7]
 [ 250   23   16   34    6]]
